### ISSUE TITLE
Status code 301 on Office 365 install

### ISSUE THREAD

**Issue by gmtandi** [lancachenet/monolithic#65] opened 2019-10-16 18:00 UTC
### Describe the issue you are having

Slow speed while installing Office 365,  Unexpected status code 301 on headers...

### How are you running the container(s)?
```
docker run \
--restart unless-stopped \
--name lancache-dns \
--detach \
-p 10.100.10.253:53:53/udp \
-e STEAMCACHE_IP="10.100.10.251 10.100.10.252 10.100.10.253" \
-e UPSTREAM_DNS=8.8.8.8 \
lancachenet/lancache-dns:latest

docker run \
--restart unless-stopped \
--name lancache \
--detach \
-v /cache/data:/data/cache \
-v /cache/logs:/data/logs \
-p 10.100.10.251:80:80 \
-p 10.100.10.252:80:80 \
-p 10.100.10.253:80:80 \
lancachenet/monolithic:latest


docker run \
--restart unless-stopped \
--name sniproxy \
--detach \
-p 10.100.10.251:443:443 \
-p 10.100.10.252:443:443 \
-p 10.100.10.253:443:443 \
lancachenet/sniproxy:latest
```

### DNS Configuration
```
DHCP serves container's IP address as name server
```
### Output of container(s)
```
2019/10/16 18:54:38 [error] 1344#1344: *6282 unexpected status code 301 in slice response while reading response header from upstream, client: 10.100.10.143, server: , request: "GET /PR/7ffbc6bf-bc32-4f92-8982-f9dd17fd3114/Office/Data/16.0.11328.20420/stream.x64.x-none.dat HTTP/1.1", subrequest: "/PR/7ffbc6bf-bc32-4f92-8982-f9dd17fd3114/Office/Data/16.0.11328.20420/stream.x64.x-none.dat", upstream: "http://173.222.196.67:80/PR/7ffbc6bf-bc32-4f92-8982-f9dd17fd3114/Office/Data/16.0.11328.20420/stream.x64.x-none.dat", host: "officecdn.microsoft.com"
```

**Comment by KsuCraig** [comment] 2019-10-25 16:20
Also getting this.

**Comment by csamsel** [comment] 2019-10-28 11:50
Microsoft - both Windows and Office updates never worked for me. I disabled it.

**Comment by unspec** [comment] 2020-02-22 12:21
Seem related to https://github.com/lancachenet/monolithic/issues/37 - further testing on Windows/Office caching required

**Comment by unspec** [comment] 2020-02-22 19:01
There does seem to be an issue with office downloads generating a slice error, confirmed by @Lepidopterist

**Comment by MathewBurnett** [comment] 2020-02-22 19:05
https://gist.github.com/MathewBurnett/0dd1c6503e008e9aa3de02027097e853
Here are is attempt to download a cab that errors.

**Comment by Lepidopterist** [comment] 2020-02-23 14:48
Hopefully, merged fix into cache-domains in https://github.com/uklans/cache-domains/pull/131.  Please can we retest?

**Comment by unspec** [comment] 2020-06-06 09:32
Closing this issue due to inactivity, feel free to reopen if needed

**Closed by unspec** 2020-06-06 09:32 UTC
Labels: bug, help wanted

**Comment by marcquark** [comment] 2020-10-15 08:02
just to leave some feedback, that change seems to have fixed the issue. at least i was able to successfully download an office update today. going to test windows udpate aswell and report in #37
